name: mini_cheff
description: Aplicativo MiniCheff - IA de alimentação infantil.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.3
  firebase_analytics: ^10.7.2
  firebase_remote_config: ^4.4.5
  camera: ^0.10.5+5
  google_mlkit_commons: ^0.7.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
